// 种子数据（与数据库无关的纯数据，供 seed.ts 与本地预览服务共用）
// type 使用字符串字面量（对应 PostgreSQL 的枚举值），避免引入 Prisma 依赖

export const resources = [
  { name: 'Psychology Today', url: 'https://www.psychologytoday.com', type: 'MEDIA', country: '美国', language: '英语', trafficLevel: '2330万/月', suitableFor: '大众/从业者', featured: true, description: '全球最大心理学门户：科普内容 + 全球最大咨询师目录（Find a Therapist）。', tags: ['科普', '咨询师目录', '双边模式'] },
  { name: '16Personalities', url: 'https://www.16personalities.com', type: 'TOOL', country: '美国', language: '多语言', trafficLevel: '1888万/月', suitableFor: '大众/学生', featured: true, description: '免费 MBTI 风格人格测试，全球流量最高的心理测评站之一。', tags: ['人格测试', '测评', '免费'] },
  { name: 'SimplePractice', url: 'https://www.simplepractice.com', type: 'SAAS', country: '美国', language: '英语', trafficLevel: '970万/月', suitableFor: '从业者', featured: true, description: '北美最大心理咨询执业管理 SaaS（预约、病历、计费、远程会谈）。', tags: ['执业SaaS', 'EHR', '工作台'] },
  { name: 'APA (美国心理学会)', url: 'https://www.apa.org', type: 'ORG', country: '美国', language: '英语', trafficLevel: '837万/月', suitableFor: '研究者/从业者', featured: true, description: 'APA 格式规范、期刊数据库 PsycINFO、执业伦理标准源头。', tags: ['协会', '权威', '期刊'] },
  { name: 'BetterHelp', url: 'https://www.betterhelp.com', type: 'THERAPY', country: '美国', language: '英语', trafficLevel: '700万/月', suitableFor: '大众', featured: true, description: '全球最大 DTC 在线心理咨询平台（订阅制）。', tags: ['在线咨询', '订阅', '导流'] },
  { name: 'Verywell Mind', url: 'https://www.verywellmind.com', type: 'MEDIA', country: '美国', language: '英语', trafficLevel: '650万/月', suitableFor: '大众', featured: true, description: 'Dotdash Meredith 旗下心理科普媒体，SEO 长文 + 医学审核体系。', tags: ['科普', 'SEO', '医学审核'] },
  { name: 'Headway', url: 'https://www.headway.co', type: 'THERAPY', country: '美国', language: '英语', trafficLevel: '530万/月', suitableFor: '大众/从业者', description: '保险内心理治疗撮合独角兽：帮咨询师接入医保网络。', tags: ['保险撮合', '咨询师匹配'] },
  { name: 'Simply Psychology', url: 'https://www.simplypsychology.org', type: 'EDU', country: '英国', language: '英语', trafficLevel: '180-300万/月', suitableFor: '学生/研究者', description: '面向学生的理论词条，学术引用超 2.6 万次，心理学学生第一站。', tags: ['词条', '教育', '理论'] },
  { name: 'Psych Central', url: 'https://psychcentral.com', type: 'MEDIA', country: '美国', language: '英语', trafficLevel: '140万/月', suitableFor: '大众', description: '老牌心理科普站，科普 + 免费自测双轮驱动。', tags: ['科普', '自测'] },
  { name: 'Mind (英国心理健康的慈善)', url: 'https://www.mind.org.uk', type: 'ORG', country: '英国', language: '英语', trafficLevel: '130万/月', suitableFor: '大众', description: '英国最大心理健康公益组织，权威科普 + 求助指南 + 政策倡导。', tags: ['公益', '求助指南', '权威'] },
  { name: 'Calm', url: 'https://www.calm.com', type: 'MEDITATION', country: '美国', language: '英语', trafficLevel: '高', suitableFor: '大众', description: '全球最大冥想 / 睡眠应用之一，网站为 App 订阅导流。', tags: ['冥想', '睡眠', 'App'] },
  { name: 'Headspace', url: 'https://www.headspace.com', type: 'MEDITATION', country: '美国/英国', language: '英语', trafficLevel: '高', suitableFor: '大众', description: '与 Calm 双雄并立的正念应用，已拓展企业 EAP 服务。', tags: ['正念', '冥想', 'EAP'] },
  { name: '7 Cups', url: 'https://www.7cups.com', type: 'THERAPY', country: '美国', language: '多语言', trafficLevel: '高', suitableFor: '大众', description: '免费情感支持社区：志愿倾听者 + 低价咨询，189 国多语言。', tags: ['互助社区', '倾听者', 'UGC'] },
  { name: 'TherapyNotes', url: 'https://www.therapynotes.com', type: 'SAAS', country: '美国', language: '英语', trafficLevel: '高', suitableFor: '从业者', description: '心理健康专用电子病历（EHR），全榜粘性之王。', tags: ['EHR', '执业SaaS', '高粘性'] },
  { name: 'Grow Therapy', url: 'https://www.growtherapy.com', type: 'THERAPY', country: '美国', language: '英语', trafficLevel: '高', suitableFor: '大众/从业者', description: 'Headway 同赛道：咨询师匹配 + 保险结算 + 执业支持三合一。', tags: ['保险撮合', '匹配'] },
  { name: 'Talkspace', url: 'https://www.talkspace.com', type: 'THERAPY', country: '美国', language: '英语', trafficLevel: '高', suitableFor: '大众', description: '上市在线治疗平台（NASDAQ:TALK），文字 + 视频治疗。', tags: ['在线咨询', '上市'] },
  { name: 'NOCD (TreatMyOCD)', url: 'https://www.treatmyocd.com', type: 'THERAPY', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '患者/大众', description: '强迫症 ERP 疗法专科平台，「单病种深耕」成功样本。', tags: ['单病种', '强迫症', 'ERP'] },
  { name: 'ADDitude', url: 'https://www.additudemag.com', type: 'MEDIA', country: '美国', language: '英语', trafficLevel: '140万/月', suitableFor: '患者/家庭', description: 'ADHD 垂直媒体，专病内容 + 网课 + 讲座变现。', tags: ['ADHD', '垂直', '单病种'] },
  { name: 'MHA (Mental Health America)', url: 'https://www.mhanational.org', type: 'ORG', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '大众/筛查', description: '免费在线心理筛查工具最大提供方（年千万次测试）。', tags: ['公益', '筛查', '免费测评'] },
  { name: 'NIMH', url: 'https://www.nimh.nih.gov', type: 'ORG', country: '美国', language: '英语', trafficLevel: '高', suitableFor: '研究者/大众', description: '美国国立精神卫生研究所，研究经费与流行病学统计权威源。', tags: ['政府', '研究', '权威'] },
  { name: 'SAMHSA', url: 'https://www.samhsa.gov', type: 'ORG', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '从业者/大众', description: '美国药物滥用与心理健康服务管理局，治疗机构查询器。', tags: ['政府', '机构查询'] },
  { name: '988 Suicide & Crisis Lifeline', url: 'https://988lifeline.org', type: 'ORG', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '危机人群', description: '美国全国自杀与危机干预热线官网，公共卫生基础设施。', tags: ['危机热线', '自杀干预'] },
  { name: 'Find a Helpline', url: 'https://findahelpline.com', type: 'ORG', country: '新西兰', language: '多语言', trafficLevel: '中', suitableFor: '危机人群', description: '全球危机热线聚合器（130+ 国家），已被 Google 引用。', tags: ['求助聚合', '热线', '全球'] },
  { name: 'Psychiatry.org', url: 'https://www.psychiatry.org', type: 'ORG', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '从业者', description: '美国精神医学学会，DSM-5-TR 诊断标准出版方。', tags: ['协会', 'DSM', '诊断标准'] },
  { name: 'Psychiatry Online', url: 'https://psychiatryonline.org', type: 'EDU', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '从业者/研究者', description: 'APA Publishing 学术平台：DSM 图书馆 + 顶刊，机构订阅制。', tags: ['学术', '出版', '期刊'] },
  { name: 'Therapist Aid', url: 'https://www.therapistaid.com', type: 'TOOL', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '从业者', description: '咨询师治疗工作表 / 心理教育素材库（免费 + 订阅）。', tags: ['素材库', '工作表', '从业者'] },
  { name: 'NovoPsych', url: 'https://novopsych.com', type: 'TOOL', country: '澳大利亚', language: '英语', trafficLevel: '中', suitableFor: '从业者', description: '面向执业者的标准化心理量表施测 / 计分 SaaS。', tags: ['量表', '计分', '从业者'] },
  { name: 'Embrace Autism', url: 'https://embrace-autism.com', type: 'TOOL', country: '加拿大', language: '英语', trafficLevel: '中', suitableFor: '大众/筛查', description: '成人自闭症自评测验库 + 科普，「专业量表在线化」典型。', tags: ['自闭症', '自测', '测评'] },
  { name: 'Attachment Project', url: 'https://attachmentproject.com', type: 'MEDIA', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '大众', description: '依恋理论主题站：免费依恋类型测试引流 → 付费课程转化。', tags: ['依恋', '主题', '测试'] },
  { name: 'HelpGuide', url: 'https://www.helpguide.org', type: 'ORG', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '大众', description: '非营利心理自助指南（与哈佛健康合作），无广告。', tags: ['公益', '自助', '指南'] },
  { name: 'Gottman Institute', url: 'https://www.gottman.com', type: 'EDU', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '从业者/夫妻', description: '婚姻家庭治疗研究机构，课程认证 + 工作坊 + 图书。', tags: ['流派IP', '婚姻', '认证'] },
  { name: 'Spring Health', url: 'https://www.springhealth.com', type: 'THERAPY', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '企业', description: 'AI 精准匹配的企业员工心理健康平台（EAP 2.0）。', tags: ['企业EAP', 'AI匹配'] },
  { name: 'Psychologies (RU)', url: 'https://www.psychologies.ru', type: 'MEDIA', country: '俄罗斯', language: '俄语', trafficLevel: '中', suitableFor: '大众', description: '俄语版《Psychologies》杂志，俄语区最大心理媒体。', tags: ['媒体', '俄语'] },
  { name: 'Doxy.me', url: 'https://doxy.me', type: 'SAAS', country: '美国', language: '英语', trafficLevel: '中', suitableFor: '从业者', description: '免费 HIPAA 合规远程视频问诊工具，被大量咨询师使用。', tags: ['远程问诊', '视频', 'HIPAA'] },
  { name: 'Halaxy', url: 'https://www.halaxy.com', type: 'SAAS', country: '澳大利亚', language: '英语', trafficLevel: '中', suitableFor: '从业者', description: '免费健康执业管理平台，靠支付与增值服务变现。', tags: ['执业SaaS', '免费'] },
];

export const helplines = [
  { name: '中国心理危机干预热线', country: '中国', language: '中文', phone: '400-161-9995', url: 'https://www.crisis.org.cn', description: '希望24热线，全国心理危机干预与自杀预防。', category: 'CRISIS' },
  { name: '北京心理援助热线', country: '中国', language: '中文', phone: '010-82951332', url: '', description: '北京回龙观医院心理危机干预热线。', category: 'CRISIS' },
  { name: '美国 988 自杀与危机生命线', country: '美国', language: '英语', phone: '988', url: 'https://988lifeline.org', description: '全美统一自杀与危机干预热线（多语言）。', category: 'CRISIS' },
  { name: '英国 Samaritans', country: '英国', language: '英语', phone: '116 123', url: 'https://www.samaritans.org', description: '24 小时情绪支持与危机倾听热线。', category: 'CRISIS' },
  { name: '澳大利亚 Lifeline', country: '澳大利亚', language: '英语', phone: '13 11 14', url: 'https://www.lifeline.org.au', description: '24 小时危机支持与自杀预防热线。', category: 'CRISIS' },
  { name: 'Find a Helpline（全球）', country: '全球', language: '多语言', phone: '', url: 'https://findahelpline.com', description: '按国家 / 语言检索的全球危机热线聚合器（130+ 国家）。', category: 'SUPPORT' },
  { name: 'MHA 免费在线筛查', country: '美国', language: '英语', phone: '', url: 'https://screening.mhanational.org', description: '心理健康美国协会提供的免费自评筛查工具。', category: 'LOW_COST' },
];

// 公共领域 / 授权公开量表的统一计分档位：0-3 四档。
// reverse=true 的题在计分时用 (3 - 得分) 处理（与 0-3 档位匹配）。
const OPTS = [
  { score: 0, label: '完全不会' },
  { score: 1, label: '好几天' },
  { score: 2, label: '一半以上的天数' },
  { score: 3, label: '几乎每天' },
];

export const assessments = [
  {
    slug: 'phq-9',
    title: 'PHQ-9 抑郁筛查量表',
    description: '患者健康问卷抑郁量表（9 项），用于抑郁症状自评与严重程度分级。结果仅供参考，不构成诊断。',
    type: 'DEPRESSION',
    questions: [
      '做事时提不起劲或没有兴趣', '感到心情低落、沮丧或绝望', '入睡困难、睡不安稳或睡眠过多',
      '感觉疲倦或没有活力', '食欲不振或吃太多',
      '觉得自己很糟，或觉得自己很失败，或让自己或家人失望',
      '对事物专注有困难，例如阅读报纸或看电视时',
      '行动或说话速度缓慢到别人已经察觉？或正好相反——变得比平常更烦躁或坐立不安',
      '有不如死掉或用某种方式伤害自己的念头',
    ].map((text, i) => ({ id: `q${i + 1}`, text, options: OPTS })),
    interpretation: {
      bands: [
        { max: 4, level: '无或极轻微', advice: '症状极轻微，保持关注即可。' },
        { max: 9, level: '轻度', advice: '建议自我调节并观察，如持续两周以上请寻求帮助。' },
        { max: 14, level: '中度', advice: '建议咨询专业心理人员。' },
        { max: 19, level: '中重度', advice: '建议尽快寻求专业评估与帮助。' },
        { max: 27, level: '重度', advice: '建议尽快就医，必要时联系危机干预热线。' },
      ],
    },
    source: 'PHQ-9（公共领域，Pfizer 授权免费使用）',
  },
  {
    slug: 'gad-7',
    title: 'GAD-7 焦虑筛查量表',
    description: '广泛性焦虑障碍量表（7 项），用于焦虑症状自评与严重程度分级。结果仅供参考，不构成诊断。',
    type: 'ANXIETY',
    questions: [
      '感到紧张、焦虑或急切', '不能够停止或控制担忧', '对各种各样的事情担忧过多',
      '很难放松下来', '由于不安而无法静坐', '变得容易烦恼或急躁',
      '感到似乎将有可怕的事情发生而害怕',
    ].map((text, i) => ({ id: `q${i + 1}`, text, options: OPTS })),
    interpretation: {
      bands: [
        { max: 4, level: '无或极轻微', advice: '症状极轻微，保持关注即可。' },
        { max: 9, level: '轻度', advice: '建议自我调节并观察。' },
        { max: 14, level: '中度', advice: '建议咨询专业心理人员。' },
        { max: 21, level: '重度', advice: '建议尽快寻求专业评估与帮助。' },
      ],
    },
    source: 'GAD-7（公共领域，Pfizer 授权免费使用）',
  },
  {
    slug: 'sds',
    title: 'SDS 抑郁自评量表（Zung）',
    description: 'Zung 抑郁自评量表（20 项），经典公版抑郁筛查工具，覆盖情绪、躯体与心理层面。结果仅供参考。',
    type: 'DEPRESSION',
    questions: [
      '我感到情绪沮丧、郁闷', '我感到早晨心情最好', '我要哭或想哭', '我夜间睡眠不好',
      '我吃饭像平时一样多', '我的性功能正常', '我感到体重下降', '我为便秘烦恼',
      '我的心跳比平时快', '我无故感到疲劳', '我的头脑像往常一样清楚', '我做事情像平时一样不感到困难',
      '我坐卧不安、难以保持平静', '我对未来感到有希望', '我比平时更容易激惹', '我觉得决定什么事很容易',
      '我感到自己是有用的和不可缺少的人', '我的生活过得很有意思', '我认为如果我死了别人会过得更好', '我对平时感兴趣的事仍然感兴趣',
    ].map((text, i) => ({
      id: `q${i + 1}`, text, options: OPTS,
      // Zung 反向计分题（正向表述 → 反向计）
      reverse: [1, 4, 10, 12, 13, 16, 17, 19].includes(i),
    })),
    interpretation: {
      bands: [
        { max: 20, level: '无或极轻微', advice: '抑郁倾向不明显，保持关注即可。' },
        { max: 40, level: '轻度', advice: '存在轻度抑郁倾向，建议自我调节并观察。' },
        { max: 60, level: '中度', advice: '中度抑郁倾向，建议咨询专业心理人员。' },
        { max: 80, level: '重度', advice: '重度抑郁倾向，建议尽快寻求专业评估与帮助。' },
      ],
    },
    source: 'SDS（Zung 1965，公版自评量表；本平台为科普化简化版，仅供示意）',
  },
  {
    slug: 'sas',
    title: 'SAS 焦虑自评量表（Zung）',
    description: 'Zung 焦虑自评量表（20 项），经典公版焦虑筛查工具，含躯体与主观焦虑维度。结果仅供参考。',
    type: 'ANXIETY',
    questions: [
      '我感到比往常更加神经过敏和焦虑', '我无缘无故感到担心', '我容易心烦意乱或感到恐慌',
      '我觉得我可能将要发疯', '我感到事事都很顺利，不会有倒霉的事发生', '我的四肢抖动和震颤',
      '我因头痛、颈痛和背痛而烦恼', '我感到无力且容易疲劳', '我感到平静，能安静坐下',
      '我感到我的心跳较快', '我因阵阵的头晕而烦恼', '我有阵阵晕倒的感觉或觉得要晕倒似的',
      '我呼气吸气都感到很容易', '我的手指和脚趾感到麻木和刺痛', '我因胃痛和消化不良而苦恼',
      '我必须频繁排尿', '我的手总是温暖而干燥', '我觉得脸发烧发红', '我容易入睡并且一夜睡得很好', '我做恶梦',
    ].map((text, i) => ({
      id: `q${i + 1}`, text, options: OPTS,
      reverse: [4, 8, 12, 16, 18].includes(i),
    })),
    interpretation: {
      bands: [
        { max: 20, level: '无或极轻微', advice: '焦虑倾向不明显，保持关注即可。' },
        { max: 40, level: '轻度', advice: '存在轻度焦虑倾向，建议自我调节并观察。' },
        { max: 60, level: '中度', advice: '中度焦虑倾向，建议咨询专业心理人员。' },
        { max: 80, level: '重度', advice: '重度焦虑倾向，建议尽快寻求专业评估与帮助。' },
      ],
    },
    source: 'SAS（Zung 1971，公版自评量表；本平台为科普化简化版，仅供示意）',
  },
  {
    slug: 'pss-10',
    title: 'PSS-10 感知压力量表',
    description: '感知压力量表（10 项），评估过去一个月你对生活不可预测、不可控、超负荷的主观感受。结果仅供参考。',
    type: 'STRESS',
    questions: [
      '因为一些意外的事，您感到紧张不安', '您感到对生活中重要的事失去了控制', '感到紧张和压力',
      '您能成功地处理恼人的生活麻烦', '您感到自己能有效地应对生活中发生的重要变化', '您感到自己能应对日常事务',
      '您感到自己能控制生活中令人恼火的事情', '您感到自己能掌控全局', '您感到心浮气躁，无法安静', '您感到困难堆积如山，无法克服',
    ].map((text, i) => ({
      id: `q${i + 1}`, text, options: OPTS,
      reverse: [3, 4, 5, 6, 7].includes(i),
    })),
    interpretation: {
      bands: [
        { max: 13, level: '低压力', advice: '感知压力较低，状态良好。' },
        { max: 26, level: '中等压力', advice: '存在中等压力，建议增加放松与休息。' },
        { max: 40, level: '高压力', advice: '感知压力较高，建议关注压力管理并寻求支持。' },
      ],
    },
    source: 'PSS-10（Cohen et al. 1983，公版量表；本平台为科普化简化版）',
  },
  {
    slug: 'rses',
    title: 'RSES 自尊量表（Rosenberg）',
    description: 'Rosenberg 自尊量表（10 项），测量整体自我价值感。结果仅供参考，不构成评估。',
    type: 'SELF_ESTEEM',
    questions: [
      '我感到自己是一个有价值的人，至少与别人不相上下', '我觉得自己有许多优点', '总的来说，我倾向于觉得自己是一个失败者',
      '我做事的能力并不比大多数人差', '我觉得自己没有什么可自豪的地方', '我对自己持有一种肯定的态度',
      '整体而言，我对自己感到满意', '我希望我能更多尊重自己', '有时我的确觉得自己一无是处', '有时我认为自己一无是处',
    ].map((text, i) => ({
      id: `q${i + 1}`, text, options: OPTS,
      reverse: [2, 4, 7, 8].includes(i),
    })),
    interpretation: {
      bands: [
        { max: 15, level: '较高自尊', advice: '自我价值感较好，保持。' },
        { max: 25, level: '中等自尊', advice: '自尊水平中等，可多关注自我肯定。' },
        { max: 30, level: '偏低自尊', advice: '自尊水平偏低，建议通过支持性关系与专业帮助提升。' },
      ],
    },
    source: 'RSES（Rosenberg 1965，公版量表；本平台为科普化简化版）',
  },
  {
    slug: 'isi',
    title: 'ISI 失眠严重程度指数',
    description: '失眠严重程度指数（7 项），快速评估入睡困难、维持睡眠困难与对日间功能的影响。结果仅供参考。',
    type: 'SLEEP',
    questions: [
      '您对目前睡眠模式的严重程度评价', '您对入睡困难的抱怨程度', '您对维持睡眠困难的抱怨程度',
      '您对过早醒来的抱怨程度', '您对目前睡眠问题对日间功能的干扰程度', '您对目前睡眠问题影响生活质量的担忧/痛苦程度',
      '您认为他人对您睡眠问题的察觉程度',
    ].map((text, i) => ({ id: `q${i + 1}`, text, options: OPTS })),
    interpretation: {
      bands: [
        { max: 7, level: '无临床意义失眠', advice: '睡眠质量尚可，保持规律作息。' },
        { max: 14, level: '阈下失眠', advice: '存在轻度睡眠问题，建议改善睡眠卫生。' },
        { max: 21, level: '中度失眠', advice: '中度失眠，建议关注并咨询专业人员。' },
        { max: 28, level: '重度失眠', advice: '重度失眠，建议尽快寻求专业评估与帮助。' },
      ],
    },
    source: 'ISI（Bastien et al. 2001；本平台为科普化简化版，正式使用请获授权）',
  },
  {
    slug: 'who-5',
    title: 'WHO-5 五维幸福感指数',
    description: '世界卫生组织五维幸福感指数（5 项），简短测量近两周主观幸福感，常用于抑郁筛查辅助。结果仅供参考。',
    type: 'WELLBEING',
    questions: [
      '我感到快乐且心情舒畅', '我感到平静且放松', '我感到充满活力且有精神', '我醒来时感到休息充分、精力恢复', '我的日常充满有趣的事情',
    ].map((text, i) => ({ id: `q${i + 1}`, text, options: OPTS })),
    interpretation: {
      bands: [
        { max: 12, level: '幸福感良好', advice: '主观幸福感较好，保持。' },
        { max: 14, level: '偏高', advice: '幸福感中等，留意情绪波动。' },
        { max: 15, level: '需关注', advice: '幸福感偏低，建议增加积极活动与社交支持。' },
      ],
    },
    source: 'WHO-5（WHO 1998，公版量表；本平台为科普化简化版）',
  },
];

// 心理资讯/科普聚合（原创内容，带来源引用与免责声明，规避版权风险）
export const articles = [
  {
    slug: 'what-is-psychology',
    title: '什么是心理学？一文读懂这门研究心智的科学',
    excerpt: '心理学不是"读心术"，而是用科学方法研究心智与行为的学科。从临床到认知，本文带你建立整体认知框架。',
    content:
      '心理学是研究心智与行为的科学，它使用观察、实验与统计等科学方法，而非直觉或经验判断。\n\n现代心理学通常分为多个分支：临床心理学关注心理障碍的评估与治疗；咨询心理学面向一般人群的发展与适应问题；认知心理学研究记忆、注意与决策；发展心理学追踪个体一生的变化；社会心理学探讨他人如何影响我们的想法与行为。\n\n一个常见误解是把心理学等同于"读心"或"精神病鉴定"。事实上，绝大多数心理学研究服务于教育、组织、健康与公共政策等广泛领域。理解这一点，能帮助你更理性地看待各类心理测评与科普内容。',
    category: 'POPSCI',
    tags: ['入门', '学科概览'],
    sourceName: '原创',
    sourceUrl: '',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-20',
  },
  {
    slug: 'depression-self-test-guide',
    title: '抑郁筛查怎么做？PHQ-9 使用与结果解读指南',
    excerpt: 'PHQ-9 是全球使用最广的抑郁筛查量表之一。本文说明它测什么、分数怎么看，以及结果之后该做什么。',
    content:
      'PHQ-9（患者健康问卷抑郁量表）由 9 个条目组成，覆盖抑郁的核心症状，包括情绪、兴趣、睡眠、食欲、注意力、动作迟滞或激越，以及自伤念头。每项按过去两周的频率计 0–3 分，总分 0–27。\n\n分数仅代表"症状负荷"，不等于诊断。一般 0–4 分属极轻微，5 分以上提示需要关注，10 分以上建议寻求专业帮助，15 分以上更应尽快评估。第 9 题（自伤念头）无论总分多少都需认真对待。\n\n重要提醒：筛查量表不能替代医生或心理治疗师的临床访谈。如果你或身边人出现持续两周以上的低落、兴趣丧失或功能下降，请及时联系专业机构或危机热线。',
    category: 'POPSCI',
    tags: ['抑郁', 'PHQ-9', '筛查'],
    sourceName: '原创（参考 APA / NIMH 公开资料）',
    sourceUrl: 'https://www.nimh.nih.gov',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-21',
  },
  {
    slug: 'anxiety-coping',
    title: '焦虑来袭时，你可以试试的 6 个科学方法',
    excerpt: '焦虑是身体的正常警报，但持续过高会消耗你。下面 6 个基于证据的方法，能帮助你在当下回到掌控感。',
    content:
      '1. 呼吸调节：尝试 4-7-8 呼吸（吸气 4 秒、屏息 7 秒、呼气 8 秒），激活副交感神经，降低生理唤醒。\n\n2. 着陆练习：说出你看到的 5 样东西、听到的 4 种声音、能触摸的 3 样物体，把注意力从"灾难化想象"拉回当下。\n\n3. 命名情绪：用具体词汇描述感受（"这是紧张，不是危险"），能降低杏仁核的过度反应。\n\n4. 限制刺激：暂时远离社交媒体与负面信息源，给大脑休息窗口。\n\n5. 身体活动：10 分钟快走可促进内啡肽释放，改善情绪。\n\n6. 规律作息：睡眠短缺会显著放大焦虑，固定作息是最便宜的"抗焦虑药"。\n\n如果焦虑频繁出现并影响工作与生活，建议通过本平台的测评工具先做自评，再考虑寻求专业支持。',
    category: 'POPSCI',
    tags: ['焦虑', '自助', '情绪调节'],
    sourceName: '原创',
    sourceUrl: '',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-22',
  },
  {
    slug: 'how-to-find-therapist',
    title: '如何挑选合适的心理咨询师？给新手的 7 条建议',
    excerpt: '第一次找咨询容易踩坑。从资质、流派到初始访谈，本文帮你建立筛选框架。',
    content:
      '1. 看资质：优先选择持有国家心理咨询师/治疗师相关资质、或心理学/精神医学专业背景的从业者。\n\n2. 看流派：认知行为疗法（CBT）、人本主义、精神动力学各有侧重，可先了解再匹配自己的议题。\n\n3. 初始访谈：多数咨询师提供低价或免费的初始访谈，用来判断"气场合不合"。\n\n4. 议题匹配：抑郁、焦虑、关系、创伤各有擅长的咨询师，别不好意思问对方经验。\n\n5. 设置与边界：明确费用、频率、取消政策与保密范围，避免后续纠纷。\n\n6. 相信感受：如果几次之后仍感到被评判或不安全，换人是正常的。\n\n7. 善用转介：严重情况（如自伤风险）应及时转介精神科，咨询与药物并不互斥。\n\n本平台的"资源导航"收录了全球优质咨询与治疗平台，可作为起步参考。',
    category: 'POPSCI',
    tags: ['咨询', '指南', '新手'],
    sourceName: '原创',
    sourceUrl: '',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-22',
  },
  {
    slug: 'sleep-and-mental-health',
    title: '睡眠与心理健康的双向关系',
    excerpt: '睡不好会加重情绪问题，情绪问题也会反过来扰乱睡眠。理解这条双向通道，是自我照护的第一步。',
    content:
      '睡眠与心理健康之间存在双向关系。一方面，失眠、早醒等睡眠问题是抑郁和焦虑的常见前驱与伴随症状；另一方面，长期睡眠剥夺会削弱情绪调节能力，放大压力反应。\n\n研究指出，规律作息、固定起床时间比"睡够时长"更能稳定生物钟。睡前 1 小时减少蓝光暴露、保持卧室凉爽黑暗，是被反复验证的睡眠卫生要点。\n\n如果你长期受睡眠困扰，可先用本平台的 ISI 失眠严重程度测评做初步自评，必要时寻求睡眠门诊或心理治疗（如 CBT-I）的专业帮助。',
    category: 'RESEARCH',
    tags: ['睡眠', '研究', '情绪'],
    sourceName: '原创（综合 NIMH / 睡眠医学综述）',
    sourceUrl: 'https://www.nimh.nih.gov',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-23',
  },
  {
    slug: 'psychology-of-social-media',
    title: '社交媒体真的让人更孤独吗？研究怎么说',
    excerpt: '"越刷越孤独"并非错觉。研究揭示了被动浏览与主动互动截然不同的心理后果。',
    content:
      '多项研究区分了社交媒体的两种使用方式：被动浏览（刷信息流而不互动）与主动互动（评论、私信、维持关系）。前者与孤独感和情绪低落更相关，后者则可能增强社会支持。\n\n一个关键机制是"上行社会比较"——看到他人精心筛选的高光时刻，容易产生"只有我过得不好"的错觉。此外，算法推荐会放大情绪化内容，形成负面循环。\n\n实用建议：把"刷"改为"聊"，给每周设定无社交媒体的时段，并警惕用平台内容替代真实关系。若使用社交媒体明显影响情绪，减少时长本身就是一种干预。',
    category: 'RESEARCH',
    tags: ['社交媒体', '研究', '孤独'],
    sourceName: '原创（综合社会心理学研究）',
    sourceUrl: '',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-23',
  },
  {
    slug: 'free-mental-health-resources-china',
    title: '国内可用的免费心理求助资源汇总',
    excerpt: '危机时刻不该因为"不知道去哪"而耽误。本文汇总国内免费、可及的心理求助入口。',
    content:
      '国内已有多条免费心理求助热线，面向不同人群：全国心理危机干预热线（400-161-9995，希望24热线）、北京心理援助热线（010-82951332）等，提供 24 小时的情绪支持与危机干预。\n\n除热线外，部分省市精神卫生中心、高校心理咨询中心与公益组织也提供低价或免费的初步评估与疏导。遇到紧急自伤风险时，请优先拨打危机热线或前往最近医院急诊。\n\n本平台"求助资源"栏目持续汇总中国及全球危机干预、支持与低价求助渠道，建议提前收藏，关键时刻用得上。',
    category: 'NEWS',
    tags: ['求助', '中国', '资源', '热线'],
    sourceName: '原创',
    sourceUrl: '',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-24',
  },
  {
    slug: 'understanding-burnout',
    title: '倦怠不是矫情：认识职业倦怠的 3 个维度',
    excerpt: '职业倦怠已被 WHO 列入国际疾病分类。它有三个可识别的维度，帮助你及早识别而非硬扛。',
    content:
      '世界卫生组织将职业倦怠定义为"长期未成功管理的职场压力"现象，包含三个维度：情绪耗竭（感到精力被掏空）、去人格化/疏离（对工作和他人变得冷漠敷衍）、以及个人成就感降低。\n\n倦怠与普通疲劳的区别在于：休息后难以恢复，且伴随对工作的消极态度转变。高危人群包括助人行业（医护、教师、咨询师）、高负荷互联网从业者。\n\n应对上，单靠"多休息"往往不够，需要审视控制感、价值感与边界。若已明显影响健康，可结合本平台的压力与情绪测评做自评，并考虑调整工作或寻求支持。',
    category: 'POPSCI',
    tags: ['倦怠', '职场', '压力'],
    sourceName: '原创（参考 WHO 公开定义）',
    sourceUrl: 'https://www.who.int',
    author: '心理资源聚合编辑部',
    publishedAt: '2026-07-24',
  },
];

// 咨询师 / 执业者目录（「转介层」核心数据）：本平台仅做信息聚合与转介，不构成诊疗建议。
// 价格为单次咨询参考价（人民币），bookingUrl 为示例占位链接，上线前需替换为各执业者真实预约入口。
export const counselors = [
  {
    id: 'c-lin-zhi',
    name: '林知',
    title: '国家二级心理咨询师',
    specialties: ['抑郁', '焦虑', '情绪调节'],
    approach: ['CBT', '人本主义'],
    region: '北京',
    remote: true,
    languages: ['中文'],
    pricePerSession: 500,
    currency: 'CNY',
    org: '北京安心心理咨询中心',
    bio: '专注于抑郁与焦虑的认知行为干预，擅长帮助青壮年建立情绪调节的日常工具。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-lin-zhi',
    rating: 4.8,
    yearsExperience: 8,
    tags: ['认知行为', '青年'],
    featured: true,
  },
  {
    id: 'c-su-wan',
    name: '苏晚',
    title: '注册心理师（伴侣与家庭）',
    specialties: ['亲密关系', '婚姻家庭', '亲子'],
    approach: ['系统式家庭治疗', 'EFT'],
    region: '上海',
    remote: true,
    languages: ['中文'],
    pricePerSession: 600,
    currency: 'CNY',
    org: '上海宁心心理咨询',
    bio: '聚焦婚恋与家庭议题，帮助伴侣改善沟通与冲突模式。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-su-wan',
    rating: 4.9,
    yearsExperience: 11,
    tags: ['家庭', '沟通'],
    featured: true,
  },
  {
    id: 'c-chen-yu',
    name: '陈屿',
    title: '临床心理学硕士',
    specialties: ['创伤', 'PTSD', '焦虑'],
    approach: ['EMDR', '精神动力学'],
    region: '广州',
    remote: true,
    languages: ['中文'],
    pricePerSession: 550,
    currency: 'CNY',
    org: '广州晴空心理工作室',
    bio: '从事创伤与创伤后应激的相关工作，提供稳定化与创伤聚焦干预。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-chen-yu',
    rating: 4.7,
    yearsExperience: 9,
    tags: ['创伤', 'EMDR'],
    featured: true,
  },
  {
    id: 'c-he-chuan',
    name: '何川',
    title: '心理咨询师',
    specialties: ['职业倦怠', '压力', '睡眠'],
    approach: ['CBT', '正念'],
    region: '深圳',
    remote: true,
    languages: ['中文'],
    pricePerSession: 480,
    currency: 'CNY',
    org: '深圳知遇心理',
    bio: '面向高压职业人群，结合认知行为与时下正念练习缓解倦怠与失眠。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-he-chuan',
    rating: 4.6,
    yearsExperience: 6,
    tags: ['职场', '正念'],
    featured: false,
  },
  {
    id: 'c-luo-yu',
    name: '罗予',
    title: '国家三级心理咨询师',
    specialties: ['青少年', '学业压力', '同伴关系'],
    approach: ['人本主义', '游戏治疗'],
    region: '成都',
    remote: false,
    languages: ['中文'],
    pricePerSession: 400,
    currency: 'CNY',
    org: '成都小树苗心理',
    bio: '面向儿童与青少年，以温和的游戏与人本方式陪伴成长议题。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-luo-yu',
    rating: 4.7,
    yearsExperience: 7,
    tags: ['青少年', '家庭'],
    featured: false,
  },
  {
    id: 'c-jiang-lin',
    name: '江临',
    title: '心理动力学取向咨询师',
    specialties: ['自我探索', '存在焦虑', '亲密关系'],
    approach: ['精神动力学'],
    region: '杭州',
    remote: true,
    languages: ['中文'],
    pricePerSession: 680,
    currency: 'CNY',
    org: '杭州听海心理咨询',
    bio: '长程心理动力学工作，适合希望深入理解自身模式、进行自我探索的来访者。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-jiang-lin',
    rating: 4.8,
    yearsExperience: 12,
    tags: ['长程', '自我成长'],
    featured: true,
  },
  {
    id: 'c-wei-an',
    name: '韦岸',
    title: '婚姻与家庭治疗师',
    specialties: ['婚姻', '家庭', '沟通'],
    approach: ['系统式', 'EFT'],
    region: '北京',
    remote: true,
    languages: ['中文'],
    pricePerSession: 720,
    currency: 'CNY',
    org: '北京伴侣工作室',
    bio: '与伴侣及家庭一同工作，改善互动循环与依恋安全。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-wei-an',
    rating: 4.9,
    yearsExperience: 14,
    tags: ['家庭', '伴侣'],
    featured: false,
  },
  {
    id: 'c-gu-yuan',
    name: '顾远',
    title: '成瘾行为心理咨询师',
    specialties: ['成瘾', '冲动控制', '网络依赖'],
    approach: ['CBT', '动机访谈'],
    region: '武汉',
    remote: false,
    languages: ['中文'],
    pricePerSession: 520,
    currency: 'CNY',
    org: '武汉清源心理',
    bio: '聚焦行为成瘾与冲动控制，结合动机访谈降低复发风险。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-gu-yuan',
    rating: 4.5,
    yearsExperience: 8,
    tags: ['成瘾', '行为'],
    featured: false,
  },
  {
    id: 'c-shao-ning',
    name: '邵宁',
    title: '老年心理关怀咨询师',
    specialties: ['老年心理', '丧亲', '孤独'],
    approach: ['人本主义', '回忆疗法'],
    region: '南京',
    remote: false,
    languages: ['中文'],
    pricePerSession: 380,
    currency: 'CNY',
    org: '南京暖阳心理',
    bio: '陪伴长者面对孤独、丧亲与生命阶段的转换。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-shao-ning',
    rating: 4.7,
    yearsExperience: 10,
    tags: ['老年', '关怀'],
    featured: false,
  },
  {
    id: 'c-tang-guo',
    name: '唐果',
    title: 'LGBTQ+ 友善咨询师',
    specialties: ['性别认同', '性少数压力', '亲密关系'],
    approach: ['人本主义', '叙事疗法'],
    region: '成都',
    remote: true,
    languages: ['中文'],
    pricePerSession: 500,
    currency: 'CNY',
    org: '成都彩虹心心理',
    bio: '为性少数群体提供友善、不评判的空间，处理认同与关系议题。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-tang-guo',
    rating: 4.8,
    yearsExperience: 7,
    tags: ['LGBTQ+', '友善'],
    featured: false,
  },
  {
    id: 'c-ye-zhou',
    name: '叶舟',
    title: '正念减压（MBSR）导师',
    specialties: ['睡眠', '压力', '慢性疼痛心理'],
    approach: ['正念', 'ACT'],
    region: '远程（全国）',
    remote: true,
    languages: ['中文'],
    pricePerSession: 450,
    currency: 'CNY',
    org: '线上正念空间',
    bio: '带领正念减压团体与个体练习，缓解压力、失眠与慢性不适带来的心理负担。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-ye-zhou',
    rating: 4.6,
    yearsExperience: 5,
    tags: ['正念', '团体'],
    featured: true,
  },
  {
    id: 'c-mo-yu',
    name: '莫语',
    title: '海外执业心理咨询师（LPCC）',
    specialties: ['跨文化适应', '移民压力', '抑郁'],
    approach: ['CBT', '多元文化咨询'],
    region: '海外（北美）',
    remote: true,
    languages: ['中文', 'English'],
    pricePerSession: 900,
    currency: 'CNY',
    org: 'NorthStar Counseling',
    bio: '服务海外华语群体，处理移民、跨文化适应与情绪困扰。本平台仅做信息聚合与转介，不构成诊疗建议。',
    avatar: null,
    bookingUrl: 'https://example.com/book/c-mo-yu',
    rating: 4.9,
    yearsExperience: 13,
    tags: ['海外', '跨文化'],
    featured: false,
  },
];

// 咨询师评价 / 社区 UGC（三期）：本平台仅做评价聚合展示，评价由用户产生，
// 上线前需配套审核与合规策略（敏感词、未成年人保护等）。此处为示例种子评价。
// 绑定到现有咨询师 id；createdAt 为展示用日期。
export const reviews = [
  { id: 'rv-1', counselorId: 'c-lin-zhi', authorName: '小鹿', rating: 5, content: '林老师很耐心，第一次咨询就没那么紧张了。给的小练习回家也能用，情绪确实比之前稳了一些。', createdAt: '2026-07-08' },
  { id: 'rv-2', counselorId: 'c-lin-zhi', authorName: '阿哲', rating: 4, content: 'CBT 的思路讲得清楚，能感觉到是在用方法帮我，而不是只听我倾诉。节奏稍快，但总体有用。', createdAt: '2026-07-12' },
  { id: 'rv-3', counselorId: 'c-su-wan', authorName: '晚风', rating: 5, content: '和伴侣一起做的几次咨询，沟通方式真的有变化。苏老师不站队，帮我们看到彼此的循环。', createdAt: '2026-07-05' },
  { id: 'rv-4', counselorId: 'c-su-wan', authorName: 'Mia', rating: 5, content: '本来是抱着试试看的心态，结果第一次就聊到了点上。对亲密关系的理解打开了新角度。', createdAt: '2026-07-15' },
  { id: 'rv-5', counselorId: 'c-chen-yu', authorName: '匿名', rating: 4, content: '创伤的部分讲得很谨慎，有稳定化的步骤，让我觉得安全。节奏慢但踏实。', createdAt: '2026-07-09' },
  { id: 'rv-6', counselorId: 'c-he-chuan', authorName: '加班狗', rating: 5, content: '针对职业倦怠给的建议很落地，正念练习坚持两周，入睡容易了些。适合高压打工人的节奏。', createdAt: '2026-07-03' },
  { id: 'rv-7', counselorId: 'c-he-chuan', authorName: '小满', rating: 4, content: '何老师对睡眠和压力的拆解很专业，不会空谈。希望后续能有线上的团体。', createdAt: '2026-07-18' },
  { id: 'rv-8', counselorId: 'c-jiang-lin', authorName: '漂流瓶', rating: 5, content: '长程做了一段时间，对自己很多模式理解深了。江老师话不多但每次都能接住。', createdAt: '2026-06-28' },
  { id: 'rv-9', counselorId: 'c-wei-an', authorName: '老周', rating: 5, content: '和妻子一起来的，韦老师帮我们把吵了多年的旧账换个方式说了出来，氛围松了很多。', createdAt: '2026-07-01' },
  { id: 'rv-10', counselorId: 'c-ye-zhou', authorName: '橙子', rating: 5, content: '正念减压的团体体验很好，叶老师引导很稳，焦虑来的时候有了可用的工具。', createdAt: '2026-07-11' },
  { id: 'rv-11', counselorId: 'c-ye-zhou', authorName: '夜猫子', rating: 4, content: '睡眠相关的练习对我帮助明显，白天没那么容易炸了。个别语音引导稍长。', createdAt: '2026-07-19' },
  { id: 'rv-12', counselorId: 'c-mo-yu', authorName: 'Lin', rating: 5, content: '在海外找华语咨询师不容易，莫老师懂跨文化那部分压力，聊起来不用反复解释背景。', createdAt: '2026-07-07' },
  { id: 'rv-13', counselorId: 'c-tang-guo', authorName: '彩虹', rating: 5, content: '作为性少数，第一次遇到不评判的空间。唐老师很温柔也很专业，推荐给需要的朋友。', createdAt: '2026-07-14' },
  { id: 'rv-14', counselorId: 'c-luo-yu', authorName: '豆豆妈', rating: 5, content: '孩子青春期的沟通问题，罗老师用游戏和温和的方式，孩子愿意开口了。', createdAt: '2026-07-16' },
];
